version: "3.4"
services:
  app:
    container_name: 'bank-service'
    image: 'bank-service'
    build:
      context: .
      dockerfile: Dockerfile.multi-stage
      target: development
    environment:
      APP_ENV: 'development'
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      BANK_SERVICE_POSTGRESQL_HOST: ${BANK_SERVICE_POSTGRESQL_HOST}
      BANK_SERVICE_POSTGRESQL_NAME: ${BANK_SERVICE_POSTGRESQL_NAME}
      BANK_SERVICE_POSTGRESQL_NAME_TEST: ${BANK_SERVICE_POSTGRESQL_NAME_TEST}
      BANK_SERVICE_POSTGRESQL_PASSWORD: ${BANK_SERVICE_POSTGRESQL_PASSWORD}
      BANK_SERVICE_POSTGRESQL_PORT: ${BANK_SERVICE_POSTGRESQL_PORT}
      BANK_SERVICE_POSTGRESQL_SSLMODE: ${BANK_SERVICE_POSTGRESQL_SSLMODE}
      BANK_SERVICE_POSTGRESQL_USERNAME: ${BANK_SERVICE_POSTGRESQL_USERNAME}
      BANK_SERVICE_REST_PORT: ${BANK_SERVICE_REST_PORT}
      BANK_SERVICE_USER1_PASSWORD: ${BANK_SERVICE_USER1_PASSWORD}
      BANK_SERVICE_USER1_EMAIL: ${BANK_SERVICE_USER1_EMAIL}
      SECONDS_BETWEEN_ATTEMPTS: ${SECONDS_BETWEEN_ATTEMPTS}
      SERVICE_NAME: ${SERVICE_NAME}
      WHITE_LIST: ${WHITE_LIST}
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - ~/.ssh:/root/.ssh
    depends_on:
      - database
  database:
    container_name: 'bank-service-postgres'
    image: 'postgres:12.3'
    environment:
      POSTGRES_DB: db
      POSTGRES_PASSWORD: ${BANK_SERVICE_POSTGRESQL_PASSWORD}
      POSTGRES_USER: root
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - '80:80'
volumes:
  postgres:
  pgadmin:
networks:
  default:
    external:
      name: bank-net
